export declare function insertHTMLBeforeBegin(element: Element, text: string): void;
export declare function insertHTMLAfterBegin(element: Element, text: string): void;
export declare function insertHTMLBeforeEnd(element: Element, text: string): void;
export declare function insertHTMLAfterEnd(element: Element, text: string): void;
export declare function insertElementBeforeBegin(targetElement: Element, element: Element): Element | null;
export declare function insertElementAfterBegin(targetElement: Element, element: Element): Element | null;
export declare function insertElementBeforeEnd(targetElement: Element, element: Element): Element | null;
export declare function insertElementAfterEnd(targetElement: Element, element: Element): Element | null;
export declare function insertTextBeforeBegin(element: Element, text: string): void;
export declare function insertTextAfterBegin(element: Element, text: string): void;
export declare function insertTextBeforeEnd(element: Element, text: string): void;
export declare function insertTextAfterEnd(element: Element, text: string): void;
